import json,re,xml.etree.ElementTree as ET
from pathlib import Path
out=Path('results/report')
def read(name):return json.loads((out/name).read_text())
imports=read('imports.json');v=read('verification.json').get('result',{}).get('results',{});soak=read('soak_30min.json').get('result',{});ui=read('dashboard_live.json')
suite=ET.parse(out/'pytest.xml').getroot().find('testsuite')
security=ET.parse(out/'security_live.xml').getroot().find('testsuite')
logs=Path('logs/acceptance_runtime.log').read_text();issues=[line for line in logs.splitlines() if re.search(r'\b(ERROR|CRITICAL)\b|Traceback \(most recent call last\)',line)]
physical=v.get('completeness',{});complete=all(not x.get('missing') and not x.get('extra') for x in physical.values()) and bool(physical)
report={'unit_tests':dict(suite.attrib),'import_failures':sum(not r['ok'] for r in imports),'all_project_imports_from_core':all('/dt4n-core/' in r.get('path','') for r in imports),'routing':read('routing_comparison.json'),'physical_completeness':complete,'verification':v,'security_live':dict(security.attrib),'soak':soak,'runtime_error_lines':issues,'bootstrap_scale':read('bootstrap_scale.json'),'dashboard_ui_stats':ui.get('stats'),'dashboard_ui_timeouts':ui.get('timeouts'),'dashboard_runtime_matches':ui.get('runtime_all_match'),'last_known':read('dashboard_last_known.json'),'video_files':[str(p) for p in (out/'demo_video').glob('*.webm')],'github_pushed':False}
(out/'final_summary.json').write_text(json.dumps(report,indent=2,ensure_ascii=False))
for i in range(5):
 p=Path(f'docs/phase-{i}/notes.md')
 p.write_text(p.read_text().split('\n\n### Kết quả chạy thực tế bản Core')[0]+'\n\n### Kết quả chạy thực tế bản Core\n\n'+{0:f"Đã tách kho từ d45cf4f; import 0/22 lỗi, các module đều từ dt4n-core. Pytest {int(suite.attrib['tests'])-int(suite.attrib['skipped'])-int(suite.attrib['failures'])-int(suite.attrib['errors'])} passed, {suite.attrib['skipped']} skipped, {suite.attrib['failures']} failed. Xem results/report/pytest.xml. Hai test bổ sung bảo vệ việc phân trang Ditto và cursor lặp.",1:'Mạng mặc định pingAll 0% dropped (20/20); topo 5 client với spec mở rộng, bw bottleneck 2 Mbps và delay 5ms đạt 0% dropped (42/42). Normal và flood có 60 snapshot mỗi kịch bản: logs/snapshots_normal.jsonl, snapshots_flood.jsonl.',2:f"Completeness vật lý: {complete}. Accuracy trạng thái link: {v.get('accuracy',{}).get('accuracy_rate')}%; event fidelity: {v.get('event_fidelity',{})}. Báo cáo docs/phase-2/verify_report.json. Độ trễ p50/p95 xem results/report/latency_up.json và latency_command.json. Soak thực chạy {soak.get('duration_s')} giây; RSS đầu/cuối {soak.get('rss_start_kib')}/{soak.get('rss_end_kib')} KiB. Accuracy này chỉ đánh giá trạng thái link.",3:f"Dashboard hiển thị 8 node/8 link, F5 giữ topology. Đã bấm UI 30 cặp disable/enable, p50/p95: {ui.get('stats')}; runtime khớp: {ui.get('runtime_all_match')}. HISTORY, ALERTS, last-known được lưu ảnh và JSON trong results/report. Video UI ở results/report/demo_video/.",4:f"Test bảo mật thật: {security.attrib}. Whitelist/payload/target/idempotency dùng audit log theo clientCorrelationId trong payload. Đã sửa test gửi timeout=0 cho phù hợp giao thức dashboard, không giảm các assert. Runtime ERROR/CRITICAL: {len(issues)} dòng trong acceptance_runtime.log. Bootstrap 20 client + 2 server đọc đủ 52 Thing, chưa xác định giới hạn capacity mạng tối đa."}[i]+'\n')
print(json.dumps({k:report[k] for k in ['unit_tests','physical_completeness','security_live','runtime_error_lines','dashboard_ui_stats','github_pushed']},indent=2))
